* File Upload Button

1. Set Up a Slot for Button Click Event: You need to connect the button's clicked signal to a slot (a function) that will handle the file upload process. This can be done using the signal-slot mechanism in Qt.
2. Implement the Slot Function: In this function, you'll use a QFileDialog to open a file chooser dialog where users can select the file they wish to upload.

** Example Code:
 ```bash
#include <QPushButton>
#include <QFileDialog>

// Slot function for the button's clicked signal
void on_uploadButton_clicked() {
    QString fileName = QFileDialog::getOpenFileName(this,
        tr("Open File"), "/path/to/your/default/folder", tr("All Files (*.*)"));
    
    // Here, you can handle the file as needed
    if (!fileName.isEmpty()) {
        // Process the file
    }
}

// In your main window or widget setup
QPushButton *uploadButton = new QPushButton("Upload File", this);
connect(uploadButton, &QPushButton::clicked, this, &YourClassName::on_uploadButton_clicked);
```

Need to replace YourClassName with the name of our class. When the button is clicked, it will open a file dialog allowing the user to choose a file. The selected file's path is stored in
fileName, which you can then use to read the file or perform other actions.
Remember to adjust the path and file types in the QFileDialog::getOpenFileName function to suit your needs.

* File Path Display Labels
1. Set Up QLabel Properties: Set the initial text of the QLabel to something like "File Path: " or leave them blank if you prefer. You can also customize their appearance as needed.
2. Update QLabel Text in the Slot Function: Modify your slot function that handles the file upload to update the text of the first QLabel with the selected file's directory path. Similarly, after your program generates an output file, update the second QLabel with its path.

** Example Code:
```bash
#include <QPushButton>
#include <QFileDialog>
#include <QLabel>

// Assuming these are member variables of your class
QLabel *inputFilePathLabel;
QLabel *outputFilePathLabel;

void on_uploadButton_clicked() {
    QString fileName = QFileDialog::getOpenFileName(this,
        tr("Open File"), "/path/to/your/default/folder", tr("All Files (*.*)"));
    
    if (!fileName.isEmpty()) {
        inputFilePathLabel->setText("Input File Path: " + fileName);
        
        // Process the file and generate output
        QString outputFilePath = ...; // Determine the output file path
        outputFilePathLabel->setText("Output File Path: " + outputFilePath);
    }
}

// In your main window or widget setup
QPushButton *uploadButton = new QPushButton("Upload File", this);
connect(uploadButton, &QPushButton::clicked, this, &YourClassName::on_uploadButton_clicked);

inputFilePathLabel = new QLabel(this);
outputFilePathLabel = new QLabel(this);
```
In this setup:

```inputFilePathLabel``` is updated with the path of the file selected by the user.
```outputFilePathLabel``` is intended to be updated with the path of the output file generated by your program.
Remember to replace placeholders and adapt the code to fit the structure of your application.
